import { writeFileSync } from "node:fs";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { buildServer } from "../src/server.js";

/**
 * Regenerates docs/TOOLS.md by connecting an in-memory client to the live
 * server and listing its tools. The manual is therefore always in sync with
 * the registered Zod schemas — never hand-edit docs/TOOLS.md.
 */
const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
const server = buildServer();
await server.connect(serverTransport);

const client = new Client({ name: "bookie-doc-gen", version: "0.0.0" });
await client.connect(clientTransport);

const { tools } = await client.listTools();

let md = "# Bookie — Tool Reference\n\n";
md += "> Generated by `npm run docs:tools`. Do not edit by hand.\n\n";
md += `Bookie exposes ${tools.length} MCP tools.\n\n`;
md += tools.map((t) => `- [\`${t.name}\`](#${t.name})`).join("\n") + "\n\n";

for (const t of tools) {
  md += `## \`${t.name}\`\n\n`;
  if (t.title) md += `**${t.title}**\n\n`;
  if (t.description) md += `${t.description}\n\n`;
  md += "**Input schema:**\n\n";
  md += "```json\n" + JSON.stringify(t.inputSchema, null, 2) + "\n```\n\n";
}

writeFileSync("docs/TOOLS.md", md);
console.log(`Wrote docs/TOOLS.md (${tools.length} tools).`);
await client.close();
await server.close();
process.exit(0);
